### ISSUE TITLE
Issues with Smooth Execution

### ISSUE THREAD

**Issue by SkyMistFA** [nopeAnon/Automated-HoloCure-Fishing#5]
The first line of code seems to interfere with the Windows interpreter invocation:
`#! C:\Users\minec\Documents\Python\holocure-fishing\fishing\Scripts\python.exe`
![2023-08-20 112832](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/89432382/c8454029-2b12-4370-a5f3-9ce9935dcedc)
I had to remove this line on my own in order to achieve proper execution.

References to image files:
`"./img/ok.png" "./img/box.png"`
For some unknown reason, I'm encountering errors on my computer. It's necessary to convert these references to absolute paths for them to work correctly. If anyone is aware of the underlying cause, please let me know.

Currently, the script's performance is unreliable, often failing to register the correct key inputs at the required times, resulting in undesirable outcomes.

**Comment by nopeAnon** [comment]
I forgot to remove that line. Its gone now. I have also changed the images to absolute path and finally made the program read your config file to get your key binds. 
For the reliability, I have intensified the search area for now (searching for every pixel now). I'm still experimenting for the best way to detect it.

**Comment by SkyMistFA** [comment]
i dont know why....
![bug-2](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/89432382/75f50425-e189-45fd-acd0-1be87a7e1fe7)
`[ WARN:0@0.117] global loadsave.cpp:248 cv::findDecoder imread_('./img/ok.png'): can't open/read file: check file path/integrity
[ WARN:1@0.118] global loadsave.cException in thread Thread-1 (continue_fishing):
pp:248 cv::findDecoder imread_('./img/box.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Traceback (most recent call last):
  File "e:\Automated\holocure_fishing.py", line 151, in <module>
    fishing()
  File "e:\Automated\holocure_fishing.py", line 91, in fishing
    self.run()
    hit_area = pyautogui.locateOnScreen("./img/box.png", confidence=0.6)
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    self._target(*self._args, **self._kwargs)
    return wrappedFunction(*args, **kwargs)
  File "e:\Automated\holocure_fishing.py", line 76, in continue_fishing
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    if pyautogui.locateOnScreen("./img/ok.png", confidence=0.6):
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 210, in locateOnScreen
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 172, in wrapper
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return wrappedFunction(*args, **kwargs)
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 378, in locateOnScreen
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyautogui\__init__.py", line 210, in locateOnScreen
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 356, in locate
    return pyscreeze.locateOnScreen(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 378, in locateOnScreen
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 205, in _locateAll_opencv
    retVal = locate(image, screenshotIm, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 356, in locate
    needleImage = _load_cv2(needleImage, grayscale)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 167, in _load_cv2
    points = tuple(locateAll(needleImage, haystackImage, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    raise IOError(
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 205, in _locateAll_opencv
OSError: Failed to read ./img/box.png because file is missing, has improper permissions, or is an unsupported or invalid format
    needleImage = _load_cv2(needleImage, grayscale)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\skyof\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyscreeze\__init__.py", line 167, in _load_cv2
    raise IOError(
OSError: Failed to read ./img/ok.png because file is missing, has improper permissions, or is an unsupported or invalid format`
However, after changing to absolute paths, no errors are encountered.

**Comment by nopeAnon** [comment]
Can you run `dir`. It seems like it can't find ok.png nor box.png. Have you properly downloaded/clone the project? Such as using `git clone https://github.com/nopeAnon/Automated-HoloCure-Fishing.git` or downloading it by zip

**Comment by SkyMistFA** [comment]
This dictionary appears to have a naming error:

`button = {
    'spacebar':0x20,
}`

It should be corrected to:

`button = {
    'space':0x20,
}`

Otherwise, it will result in an error message:

`Traceback (most recent call last):
  File "E:\Automated\holocure_fishing.py", line 151, in <module>
    fishing()
  File "E:\Automated\holocure_fishing.py", line 137, in fishing
    press(press_button)
  File "E:\Automated\holocure_fishing.py", line 69, in press
    win.SendMessage(win32con.WM_KEYDOWN, button[button_key], 0)
`

**Comment by SkyMistFA** [comment]
I have downloaded the complete ZIP file.
![bug-3](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/89432382/bc02e3ce-2da4-4539-a2fb-8c78913fd6a2)

**Comment by SkyMistFA** [comment]
The script often fails, seemingly due to slow input. Holocure is being run in a 1280x720 windowed mode.
![fail](https://github.com/nopeAnon/Automated-HoloCure-Fishing/assets/89432382/944698dd-afd7-40af-ab50-10af22f09c95)

**Comment by sssnakeke** [comment]
It's working perfectly fine on my end. If you're having timing issues, that could be due to how time.sleep is set up when you first cloned it. I had to readjust the values myself since I was originally using a diff rod (the original values worked pretty well on the gold rod). I also noticed a bit of spam from the input itself when it would mistime itself, then it would try to correct itself, but by then the note would have passed, and you end up notelocking and failing the catch, so just add another sleep after button down at line 67

**Comment by nopeAnon** [comment]
> This dictionary appears to have a naming error:
> 
> `button = { 'spacebar':0x20, }`
> 
> It should be corrected to:
> 
> `button = { 'space':0x20, }`

Fixed

>so just add another sleep after button down at line 67

Ok, that fixes things by a lot.

**Comment by SkyMistFA** [comment]
Thank you so much. After adding an additional sleep on line 67, the script runs very smoothly.
